Repository antlr/antlr3, pull requests merged in 2022-04, with the labels that each got.

#201 change source compatibility to 1.8 and enabke github workflows
  .github/workflows/main.yml
  pom.xml
Labels: comp:build, cleanup

#185 Change Wiki URLs to theantlrguy.atlassian.net in README.txt
  README.txt
Labels: cleanup, doc

#207 Bazel support
  .gitignore
  BUILD.bazel
  WORKSPACE.bazel
  contributors.txt
  runtime/Java/src/main/java/org/antlr/runtime/debug/DebugTreeAdaptor.java
  tool/src/BUILD.bazel
  tool/src/test/java/org/antlr/test/TestAutoAST.java
  tool/src/test/java/org/antlr/test/TestCharDFAConversion.java
  tool/src/test/java/org/antlr/test/TestDFAConversion.java
  tool/src/test/java/org/antlr/test/TestSemanticPredicateEvaluation.java
  tool/src/test/java/org/antlr/test/TestSemanticPredicates.java
Labels: comp:build
